student_mgmt_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
]

students/urls.py
from django.urls import path
from .import views

app_name='students'

urlpatterns=[
    path('',views.list_Students, name='list'),
    path('add/',views.add_Student, name='add'),
    path('edit/<int:pk>/',views.edit_Student, name='edit'),
    path('delete/<int:pk>/',views.delete_Student, name='delete'),
]

students/models.py
from django.db import models

#Models ==> module name
#Model helper class

class Students(models.Model):

    Gender_choices=[
        ('M', 'Male'),
        ('F', 'Female')
    ]

    roll_no=models.PositiveIntegerField(unique=True)
    name=models.CharField(max_length=20)
    email=models.EmailField()
    phone_no=models.CharField(max_length=10)
    course=models.CharField(max_length=50)
    year=models.PositiveIntegerField()
    dob=models.DateTimeField()
    gender=models.CharField(max_length=2, choices=Gender_choices)
    address=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True) #10:00
    updated_at=models.DateTimeField(auto_now=True) #11:00

    def __str__(self):
        return self.name


    # auto_now_add ==> stores the date & time when the record is created.
    # Value is set only once, never changes again.
    
    # auto_now ==> stores the date & time of the last update
    # updates every-time save() is called.

# Create your models here.

students/forms.py
from django import forms
from .models import Students

class DateInput(forms.DateInput):
    input_type='date'

class StudentForm(forms.ModelForm):
    class Meta:
        model=Students
        fields=['roll_no','name','email','phone_no','course','year','dob','gender','address']
        widgets={'dob': DateInput(), 'address': forms.Textarea(attrs={'rows':3})}

students/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from .models import Students
from .forms import StudentForm

# Create your views here.

def list_Students(request):
    q=request.GET.get('q','').strip()
    students=Students.objects.all()
    if q:
        students=students.filter(name__icontains=q)
        students.filter(roll_no__icontains=q)
        students.filter(course__icontains=q)
    return render(request,'students/list.html',{'students':students, 'q':q})

def add_Student(request):
    if request.method=='POST':
        form=StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student added Successfully')
            return redirect('students:list')
    else:
        form=StudentForm()
    return render(request, 'students/form.html',{'form':form, 'title':'Add Student'})

def edit_Student(request,pk):
    student=get_object_or_404(Students,pk=pk)
    
    if request.method=='POST':
        form=StudentForm(request.POST,instance=student)
        if form.is_valid():
            form.save()
            messages.success(request,'Student updated Successfully!')
            return redirect('students:list')
    else:
        form=StudentForm(instance=student)
    return render(request,'students/form.html', {'form':form, 'title':'Edit Student'})

def delete_Student(request,pk):
    student=get_object_or_404(Students,pk=pk)
    
    if request.method=='POST':
        student.delete()
        messages.success(request,'Student deleted Successfully!')
        return redirect('students:list')
    return render(request,'students/confirm_delete.html',{'student':student})

students/templates/students/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<header>
    <h1>Student Management System</h1>
    <nav>
        <a href="{% url 'students:list' %}">Dashboard</a>
        <a href="{% url 'students:add' %}">Add Student</a>
    </nav>
</header>
<main>
    {% if messages %}
    {% for message in messages %}
        <p class="{{message.tags}}">{{message}}</p>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

students/templates/students/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'students/base.html' %}
    {% block title %}Delete Student{% endblock %}
    {% block content %}
    <h2>Delete Student</h2>
    <p>Are you sure you want to delete student: <strong>{{student.name}}({{student.roll_no}})</strong></p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'students:list' %}">Cancel</a>
    </form>
    {% endblock %}
</body>
</html>

students/templates/students/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'students/base.html' %}
    {% block title %}{{ title }}{% endblock %}
    {% block content %}
    <h2>{{ title }}</h2>
    <form method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <button type="submit">Save</button>
        <a href="{% url 'students:list' %}">Cancel</a>
    </form>
    {% endblock %}
</body>
</html>

students/templates/students/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'students/base.html' %}
    {% block title %}Students Dashboard{% endblock %}
    {% block content %}
    <h2>Students</h2>
    <form method="get">
        <input type="text" name="q" value="{{ q }}" placeholder="Search">
        <button type="Submit">Search</button>
    </form>
    <table border="1" cellpadding="8" cellspacing="0">
        <tr> <br>
            <th>Roll No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Course</th>
            <th>Year</th>
            <th>Actions</th>
        </tr>
        {% for s in students %}
        <tr>
            <td>{{ s.roll_no }}</td>
            <td>{{ s.name }}</td>
            <td>{{ s.email }}</td>
            <td>{{ s.course }}</td>
            <td>{{ s.year }}</td>
            <td>
                <a href="{% url 'students:edit' s.pk %}">Edit</a>
                <a href="{% url 'students:delete' s.pk %}">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr><td colspan="6">No students found</td></tr>
        {% endfor %}
    </table>
    {% endblock %}
</body>
</html>